root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
 4.4/community-and-support/community/readme: 4.5/community-and-support/community/README.md
 4.4/community-and-support/enterprise-support: 4.5/community-and-support/enterprise-support.md
 4.4/getting-started/api-storage-and-control-options/configure-the-gateway-to-load-apis-from-local-configmaps: 4.5/getting-started/api-storage-and-control-options/configure-the-gateway-to-load-apis-from-local-configmaps.md
 4.4/getting-started/api-storage-and-control-options/readme: 4.5/getting-started/api-storage-and-control-options/README.md
 4.4/getting-started/api-storage-and-control-options/store-apis-in-local-configmaps: 4.5/getting-started/api-storage-and-control-options/store-apis-in-local-configmaps.md
 4.4/getting-started/api-storage-and-control-options/use-a-central-apim-repository: 4.5/getting-started/api-storage-and-control-options/use-a-central-apim-repository.md
 4.4/getting-started/installation/cluster-vs-namespaced-install: 4.5/getting-started/installation/cluster-vs-namespaced-install.md
 4.4/getting-started/installation/install-with-helm: 4.5/getting-started/installation/install-with-helm.md
 4.4/getting-started/installation/readme: 4.5/getting-started/installation/README.md
 4.4/getting-started/quickstart-guide: 4.5/getting-started/quickstart-guide.md
 4.4/guides/create-your-own-helm-charts: 4.5/guides/create-your-own-helm-charts.md
 4.4/guides/db-less-mode: 4.5/guides/db-less-mode.md
 4.4/guides/define-an-apim-service-account-for-gko: 4.5/guides/define-an-apim-service-account-for-gko.md
 4.4/guides/deploy-apis-to-a-gateway: 4.5/guides/deploy-apis-to-a-gateway.md
 4.4/guides/export-an-api-as-a-kubernetes-manifest: 4.5/guides/export-an-api-as-a-kubernetes-manifest.md
 4.4/guides/gravitee-ingress-controller: 4.5/guides/gravitee-ingress-controller.md
 4.4/guides/manage-api-documentation-pages: 4.5/guides/manage-api-documentation-pages.md
 4.4/guides/manage-api-groups-and-members: 4.5/guides/manage-api-groups-and-members.md
 4.4/guides/multi-environment-architecture: 4.5/guides/multi-environment-architecture.md
 4.4/guides/publish-apis-to-the-portal: 4.5/guides/publish-apis-to-the-portal.md
 4.4/guides/templating: 4.5/guides/templating.md
 4.4/overview/compatibility-and-limitations: 4.5/overview/compatibility-and-limitations.md
 4.4/overview/custom-resource-definitions/apidefinition: 4.5/overview/custom-resource-definitions/apidefinition.md
 4.4/overview/custom-resource-definitions/apiresource: 4.5/overview/custom-resource-definitions/apiresource.md
 4.4/overview/custom-resource-definitions/apiv4definition: 4.5/overview/custom-resource-definitions/apiv4definition.md
 4.4/overview/custom-resource-definitions/application: 4.5/overview/custom-resource-definitions/application.md
 4.4/overview/custom-resource-definitions/managementcontext: 4.5/overview/custom-resource-definitions/managementcontext.md
 4.4/overview/custom-resource-definitions/readme: 4.5/overview/custom-resource-definitions/README.md
 4.4/overview/example-architecture: 4.5/overview/example-architecture.md
 4.4/readme: 4.5/README.md
 4.4/reference/api-reference: 4.5/reference/api-reference.md
 4.4/releases-and-changelog/changelog/gko-4.4.x: 4.5/releases-and-changelog/changelog/gko-4.5.x.md
 4.4/releases-and-changelog/changelog/readme: 4.5/releases-and-changelog/changelog/README.md
 4.4/releases-and-changelog/release-notes/readme: 4.5/releases-and-changelog/release-notes/README.md
 4.4/summary: 4.5/SUMMARY.md