root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
 4.0/community-and-support/community/readme: 4.1/community-and-support/community/README.md
 4.0/community-and-support/enterprise-support: 4.1/community-and-support/enterprise-support.md
 4.0/getting-started/configuration/configure-am-api/internal-api: 4.1/getting-started/configuration/configure-am-api/internal-api.md
 4.0/getting-started/configuration/configure-am-api/readme: 4.1/getting-started/configuration/configure-am-api/README.md
 4.0/getting-started/configuration/configure-am-console: 4.1/getting-started/configuration/configure-am-console.md
 4.0/getting-started/configuration/configure-am-gateway/internal-api: 4.1/getting-started/configuration/configure-am-gateway/internal-api.md
 4.0/getting-started/configuration/configure-am-gateway/readme: 4.1/getting-started/configuration/configure-am-gateway/README.md
 4.0/getting-started/configuration/configure-monitoring: 4.1/getting-started/configuration/configure-monitoring.md
 4.0/getting-started/configuration/configure-reporters: 4.1/getting-started/configuration/configure-reporters.md
 4.0/getting-started/configuration/configure-repositories: 4.1/getting-started/configuration/configure-repositories.md
 4.0/getting-started/configuration/readme: 4.1/getting-started/configuration/README.md
 4.0/getting-started/install-and-upgrade-guides/breaking-changes-for-access-management: 4.1/getting-started/install-and-upgrade-guides/breaking-changes-for-access-management.md
 4.0/getting-started/install-and-upgrade-guides/configure-a-production-ready-am-environment: 4.1/getting-started/install-and-upgrade-guides/configure-a-production-ready-am-environment.md
 4.0/getting-started/install-and-upgrade-guides/deploy-in-kubernetes: 4.1/getting-started/install-and-upgrade-guides/deploy-in-kubernetes.md
 4.0/getting-started/install-and-upgrade-guides/install-on-amazon: 4.1/getting-started/install-and-upgrade-guides/install-on-amazon.md
 4.0/getting-started/install-and-upgrade-guides/install-on-red-hat: 4.1/getting-started/install-and-upgrade-guides/install-on-red-hat.md
 4.0/getting-started/install-and-upgrade-guides/install-with-.zip: 4.1/getting-started/install-and-upgrade-guides/install-with-.zip.md
 4.0/getting-started/install-and-upgrade-guides/quick-install: 4.1/getting-started/install-and-upgrade-guides/quick-install.md
 4.0/getting-started/install-and-upgrade-guides/readme: 4.1/getting-started/install-and-upgrade-guides/README.md
 4.0/getting-started/install-and-upgrade-guides/run-in-docker/docker-compose-install: 4.1/getting-started/install-and-upgrade-guides/run-in-docker/docker-compose-install.md
 4.0/getting-started/install-and-upgrade-guides/run-in-docker/docker-images-install: 4.1/getting-started/install-and-upgrade-guides/run-in-docker/docker-images-install.md
 4.0/getting-started/install-and-upgrade-guides/run-in-docker/readme: 4.1/getting-started/install-and-upgrade-guides/run-in-docker/README.md
 4.0/getting-started/install-and-upgrade-guides/upgrade-guide: 4.1/getting-started/install-and-upgrade-guides/upgrade-guide.md
 4.0/getting-started/tutorial-getting-started-with-am/add-custom-claims-to-tokens: 4.1/getting-started/tutorial-getting-started-with-am/add-custom-claims-to-tokens.md
 4.0/getting-started/tutorial-getting-started-with-am/configure-a-flow: 4.1/getting-started/tutorial-getting-started-with-am/configure-a-flow.md
 4.0/getting-started/tutorial-getting-started-with-am/get-user-profile-information: 4.1/getting-started/tutorial-getting-started-with-am/get-user-profile-information.md
 4.0/getting-started/tutorial-getting-started-with-am/login-to-am-console: 4.1/getting-started/tutorial-getting-started-with-am/login-to-am-console.md
 4.0/getting-started/tutorial-getting-started-with-am/readme: 4.1/getting-started/tutorial-getting-started-with-am/README.md
 4.0/getting-started/tutorial-getting-started-with-am/secure-your-apis/configure-generic-oauth2-authorization-server: 4.1/getting-started/tutorial-getting-started-with-am/secure-your-apis/configure-generic-oauth2-authorization-server.md
 4.0/getting-started/tutorial-getting-started-with-am/secure-your-apis/configure-gravitee.io-access-management: 4.1/getting-started/tutorial-getting-started-with-am/secure-your-apis/configure-gravitee.io-access-management.md
 4.0/getting-started/tutorial-getting-started-with-am/secure-your-apis/readme: 4.1/getting-started/tutorial-getting-started-with-am/secure-your-apis/README.md
 4.0/getting-started/tutorial-getting-started-with-am/set-up-your-first-application: 4.1/getting-started/tutorial-getting-started-with-am/set-up-your-first-application.md
 4.0/guides/administration: 4.1/guides/administration.md
 4.0/guides/alerts/manage-alerts: 4.1/guides/alerts/manage-alerts.md
 4.0/guides/alerts/notification-channels: 4.1/guides/alerts/notification-channels.md
 4.0/guides/alerts/readme: 4.1/guides/alerts/README.md
 4.0/guides/am-expression-language: 4.1/guides/am-expression-language.md
 4.0/guides/applications: 4.1/guides/applications.md
 4.0/guides/audit-trail: 4.1/guides/audit-trail.md
 4.0/guides/auth-protocols/ciba: 4.1/guides/auth-protocols/ciba.md
 4.0/guides/auth-protocols/oauth-2.0/best-practices: 4.1/guides/auth-protocols/oauth-2.0/best-practices.md
 4.0/guides/auth-protocols/oauth-2.0/extension-grants: 4.1/guides/auth-protocols/oauth-2.0/extension-grants.md
 4.0/guides/auth-protocols/oauth-2.0/proof-key-for-code-exchange-pkce: 4.1/guides/auth-protocols/oauth-2.0/proof-key-for-code-exchange-pkce.md
 4.0/guides/auth-protocols/oauth-2.0/readme: 4.1/guides/auth-protocols/oauth-2.0/README.md
 4.0/guides/auth-protocols/oauth-2.0/refresh-tokens: 4.1/guides/auth-protocols/oauth-2.0/refresh-tokens.md
 4.0/guides/auth-protocols/oauth-2.0/which-flow-should-i-use: 4.1/guides/auth-protocols/oauth-2.0/which-flow-should-i-use.md
 4.0/guides/auth-protocols/open-banking: 4.1/guides/auth-protocols/open-banking.md
 4.0/guides/auth-protocols/openid-connect: 4.1/guides/auth-protocols/openid-connect.md
 4.0/guides/auth-protocols/readme: 4.1/guides/auth-protocols/README.md
 4.0/guides/auth-protocols/saml-2.0: 4.1/guides/auth-protocols/saml-2.0.md
 4.0/guides/auth-protocols/scim-2.0: 4.1/guides/auth-protocols/scim-2.0.md
 4.0/guides/auth-protocols/uma-2.0: 4.1/guides/auth-protocols/uma-2.0.md
 4.0/guides/bot-detection: 4.1/guides/bot-detection.md
 4.0/guides/branding/css-custom-variables-reference: 4.1/guides/branding/css-custom-variables-reference.md
 4.0/guides/branding/language-default-properties-reference: 4.1/guides/branding/language-default-properties-reference.md
 4.0/guides/branding/readme: 4.1/guides/branding/README.md
 4.0/guides/certificates: 4.1/guides/certificates.md
 4.0/guides/developer-contributions: 4.1/guides/developer-contributions.md
 4.0/guides/device-identifier: 4.1/guides/device-identifier.md
 4.0/guides/flows: 4.1/guides/flows.md
 4.0/guides/identity-providers/create-an-identity-provider: 4.1/guides/identity-providers/create-an-identity-provider.md
 4.0/guides/identity-providers/database-identity-providers/inline: 4.1/guides/identity-providers/database-identity-providers/inline.md
 4.0/guides/identity-providers/database-identity-providers/jdbc: 4.1/guides/identity-providers/database-identity-providers/jdbc.md
 4.0/guides/identity-providers/database-identity-providers/mongodb: 4.1/guides/identity-providers/database-identity-providers/mongodb.md
 4.0/guides/identity-providers/database-identity-providers/readme: 4.1/guides/identity-providers/database-identity-providers/README.md
 4.0/guides/identity-providers/enterprise-identity-providers/active-directory-ldap: 4.1/guides/identity-providers/enterprise-identity-providers/active-directory-ldap.md
 4.0/guides/identity-providers/enterprise-identity-providers/cas: 4.1/guides/identity-providers/enterprise-identity-providers/cas.md
 4.0/guides/identity-providers/enterprise-identity-providers/http-web-service: 4.1/guides/identity-providers/enterprise-identity-providers/http-web-service.md
 4.0/guides/identity-providers/enterprise-identity-providers/kerberos: 4.1/guides/identity-providers/enterprise-identity-providers/kerberos.md
 4.0/guides/identity-providers/enterprise-identity-providers/readme: 4.1/guides/identity-providers/enterprise-identity-providers/README.md
 4.0/guides/identity-providers/enterprise-identity-providers/saml-2.0: 4.1/guides/identity-providers/enterprise-identity-providers/saml-2.0.md
 4.0/guides/identity-providers/legal-identity-providers/franceconnect: 4.1/guides/identity-providers/legal-identity-providers/franceconnect.md
 4.0/guides/identity-providers/legal-identity-providers/readme: 4.1/guides/identity-providers/legal-identity-providers/README.md
 4.0/guides/identity-providers/readme: 4.1/guides/identity-providers/README.md
 4.0/guides/identity-providers/social-identity-providers/azure-ad: 4.1/guides/identity-providers/social-identity-providers/azure-ad.md
 4.0/guides/identity-providers/social-identity-providers/facebook: 4.1/guides/identity-providers/social-identity-providers/facebook.md
 4.0/guides/identity-providers/social-identity-providers/github: 4.1/guides/identity-providers/social-identity-providers/github.md
 4.0/guides/identity-providers/social-identity-providers/linkedin: 4.1/guides/identity-providers/social-identity-providers/linkedin.md
 4.0/guides/identity-providers/social-identity-providers/readme: 4.1/guides/identity-providers/social-identity-providers/README.md
 4.0/guides/identity-providers/social-identity-providers/salesforce: 4.1/guides/identity-providers/social-identity-providers/salesforce.md
 4.0/guides/identity-providers/social-identity-providers/twitter: 4.1/guides/identity-providers/social-identity-providers/twitter.md
 4.0/guides/identity-providers/user-and-role-mapping: 4.1/guides/identity-providers/user-and-role-mapping.md
 4.0/guides/login/adaptive-multi-factor-authentication: 4.1/guides/login/adaptive-multi-factor-authentication.md
 4.0/guides/login/hide-login-form: 4.1/guides/login/hide-login-form.md
 4.0/guides/login/identifier-first-login-flow: 4.1/guides/login/identifier-first-login-flow.md
 4.0/guides/login/passwordless-w3c-webauthn: 4.1/guides/login/passwordless-w3c-webauthn.md
 4.0/guides/login/readme: 4.1/guides/login/README.md
 4.0/guides/login/redirect-users-after-login: 4.1/guides/login/redirect-users-after-login.md
 4.0/guides/login/remember-authentication-device: 4.1/guides/login/remember-authentication-device.md
 4.0/guides/login/risk-based-mfa: 4.1/guides/login/risk-based-mfa.md
 4.0/guides/login/silent-reauthentication: 4.1/guides/login/silent-reauthentication.md
 4.0/guides/login/step-up-authentication: 4.1/guides/login/step-up-authentication.md
 4.0/guides/multi-factor-authentication/alternative-methods: 4.1/guides/multi-factor-authentication/alternative-methods.md
 4.0/guides/multi-factor-authentication/factors: 4.1/guides/multi-factor-authentication/factors.md
 4.0/guides/multi-factor-authentication/mfa-security: 4.1/guides/multi-factor-authentication/mfa-security.md
 4.0/guides/multi-factor-authentication/mfa-with-fido2: 4.1/guides/multi-factor-authentication/mfa-with-fido2.md
 4.0/guides/multi-factor-authentication/readme: 4.1/guides/multi-factor-authentication/README.md
 4.0/guides/multi-factor-authentication/recovery-codes: 4.1/guides/multi-factor-authentication/recovery-codes.md
 4.0/guides/multi-factor-authentication/reset-mfa: 4.1/guides/multi-factor-authentication/reset-mfa.md
 4.0/guides/prologue: 4.1/guides/prologue.md
 4.0/guides/resources/readme: 4.1/guides/resources/README.md
 4.0/guides/resources/smtp-resource: 4.1/guides/resources/smtp-resource.md
 4.0/guides/resources/twilio: 4.1/guides/resources/twilio.md
 4.0/guides/security-domains: 4.1/guides/security-domains.md
 4.0/guides/session-management: 4.1/guides/session-management.md
 4.0/guides/user-management/groups: 4.1/guides/user-management/groups.md
 4.0/guides/user-management/password-policy: 4.1/guides/user-management/password-policy.md
 4.0/guides/user-management/readme: 4.1/guides/user-management/README.md
 4.0/guides/user-management/roles: 4.1/guides/user-management/roles.md
 4.0/guides/user-management/scim-2.0: 4.1/guides/user-management/scim-2.0.md
 4.0/guides/user-management/self-service-account-management: 4.1/guides/user-management/self-service-account-management.md
 4.0/guides/user-management/user-consent: 4.1/guides/user-management/user-consent.md
 4.0/guides/user-management/user-registration: 4.1/guides/user-management/user-registration.md
 4.0/guides/user-management/users: 4.1/guides/user-management/users.md
 4.0/overview/am-architecture: 4.1/overview/am-architecture.md
 4.0/overview/open-source-vs-enterprise-am/readme: 4.1/overview/open-source-vs-enterprise-am/README.md
 4.0/overview/plugins/compatibility-matrices: 4.1/overview/plugins/compatibility-matrices.md
 4.0/overview/plugins/readme: 4.1/overview/plugins/README.md
 4.0/readme: 4.1/README.md
 4.0/reference/am-api-reference: 4.1/reference/am-api-reference.md
 4.0/releases-and-changelog/changelog/am-4.0.x: 4.1/releases-and-changelog/changelog/am-4.1.x.md
 4.0/releases-and-changelog/changelog/readme: 4.1/releases-and-changelog/changelog/README.md
 4.0/releases-and-changelog/release-notes/am-4.0: README.md
 4.0/releases-and-changelog/release-notes/readme: 4.1/releases-and-changelog/release-notes/README.md
 4.0/summary: 4.1/SUMMARY.md