root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
 gko-4.11: releases-and-changelog/release-notes/gko-4.12.md
 new-release: README.md
 releases-and-changelog/changelog/gko-4.10.x: releases-and-changelog/release-notes/gko-4.12.md
 releases-and-changelog/changelog/gko-4.11.x: releases-and-changelog/release-notes/gko-4.12.md
 releases-and-changelog/changelog/gko-4.3.x: releases-and-changelog/release-notes/gko-4.12.md
 releases-and-changelog/changelog/gko-4.4.x: releases-and-changelog/release-notes/gko-4.12.md
 releases-and-changelog/changelog/gko-4.5.x: releases-and-changelog/release-notes/gko-4.12.md
 releases-and-changelog/changelog/gko-4.6.x: releases-and-changelog/release-notes/gko-4.12.md
 releases-and-changelog/changelog/gko-4.7.x: releases-and-changelog/release-notes/gko-4.12.md
 releases-and-changelog/changelog/gko-4.8.x: releases-and-changelog/release-notes/gko-4.12.md
 releases-and-changelog/changelog/gko-4.9.x: releases-and-changelog/release-notes/gko-4.12.md
 releases-and-changelog/release-notes/gko-4.3: releases-and-changelog/release-notes/gko-4.12.md
 releases-and-changelog/release-notes/gko-4.4: releases-and-changelog/release-notes/gko-4.12.md
 releases-and-changelog/release-notes/gko-4.5: releases-and-changelog/release-notes/gko-4.12.md
 releases-and-changelog/release-notes/gko-4.6: releases-and-changelog/release-notes/gko-4.12.md
 releases-and-changelog/release-notes/gko-4.7: releases-and-changelog/release-notes/gko-4.12.md
 releases-and-changelog/release-notes/gko-4.8: releases-and-changelog/release-notes/gko-4.12.md
 releases-and-changelog/release-notes/gko-4.9: releases-and-changelog/release-notes/gko-4.12.md
