StylesPath = "vale/styles"

MinAlertLevel = suggestion

Vocab = docs

Packages = Microsoft

IgnoredScopes = code, tt, img, url, a, link, blockquote

SkippedScopes = script, style, pre, figure, code

# Treat MDX as Markdown
[formats]
mdx = md

[*.{md,mdx}]

BasedOnStyles = Microsoft, docs
CommentDelimiters = {/*, */}

# Disable rules that give too many false positives
Microsoft.Passive = NO
Microsoft.Acronyms = NO
Microsoft.Headings = NO
Microsoft.Parens = NO
Microsoft.Foreign = NO
Microsoft.GeneralURL = NO
Microsoft.Accessibility = NO
Microsoft.Contractions = NO

# Ignore code surrounded by backticks or plus sign, parameters defaults, URLs, and angle brackets.
TokenIgnores = (<\/?[A-Z].+>), (\x60[^\n\x60]+\x60), ([^\n]+=[^\n]*), (\+[^\n]+\+), (http[^\n]+\[)
BlockIgnores = (```[a-z]*[\s\S]*?\n```), (---[\s\S]*?\n---), (keywords: [\s\S]*?\n), (description: [\s\S]*?\n)
