root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
 4.3/.gitbook/includes/for-optimal-performance-and...: README.md
 4.3/community-and-support/community/readme: 4.4/community-and-support/community/README.md
 4.3/community-and-support/enterprise-support: 4.4/community-and-support/enterprise-support.md
 4.3/overview/compatibility-and-limitations: 4.4/overview/compatibility-and-limitations.md
 4.3/readme: README.md
 4.3/reference/api-reference: 4.4/reference/api-reference.md
 4.3/releases-and-changelog/changelog/gko-4.3.x: 4.4/releases-and-changelog/changelog/gko-4.4.x.md
 4.3/releases-and-changelog/changelog/readme: 4.4/releases-and-changelog/changelog/README.md
 4.3/releases-and-changelog/release-notes/gko-4.3: README.md
 4.3/releases-and-changelog/release-notes/gko-4.4: README.md
 4.3/releases-and-changelog/release-notes/readme: 4.4/releases-and-changelog/release-notes/README.md
 4.3/summary: README.md