root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
 4.4/community-and-support/community/readme: 4.5/community-and-support/community/README.md
 4.4/community-and-support/enterprise-support: 4.5/community-and-support/enterprise-support.md
 4.4/getting-started/configuration/configure-am-api/internal-api: 4.5/getting-started/configuration/configure-am-api/internal-api.md
 4.4/getting-started/configuration/configure-am-api/readme: 4.5/getting-started/configuration/configure-am-api/README.md
 4.4/getting-started/configuration/configure-am-console: 4.5/getting-started/configuration/configure-am-console.md
 4.4/getting-started/configuration/configure-am-gateway/internal-api: 4.5/getting-started/configuration/configure-am-gateway/internal-api.md
 4.4/getting-started/configuration/configure-am-gateway/readme: 4.5/getting-started/configuration/configure-am-gateway/README.md
 4.4/getting-started/configuration/configure-monitoring: 4.5/getting-started/configuration/configure-monitoring.md
 4.4/getting-started/configuration/configure-reporters: README.md
 4.4/getting-started/configuration/configure-repositories: 4.5/getting-started/configuration/configure-repositories.md
 4.4/getting-started/configuration/readme: 4.5/getting-started/configuration/README.md
 4.4/getting-started/configuration/secret-providers: 4.5/getting-started/configuration/secret-providers.md
 4.4/getting-started/install-and-upgrade-guides/breaking-changes-for-access-management: 4.5/getting-started/install-and-upgrade-guides/breaking-changes-for-access-management.md
 4.4/getting-started/install-and-upgrade-guides/configure-a-production-ready-am-environment: 4.5/getting-started/install-and-upgrade-guides/configure-a-production-ready-am-environment.md
 4.4/getting-started/install-and-upgrade-guides/deploy-in-kubernetes: 4.5/getting-started/install-and-upgrade-guides/deploy-in-kubernetes.md
 4.4/getting-started/install-and-upgrade-guides/install-on-amazon: 4.5/getting-started/install-and-upgrade-guides/install-on-amazon.md
 4.4/getting-started/install-and-upgrade-guides/install-on-red-hat: 4.5/getting-started/install-and-upgrade-guides/install-on-red-hat.md
 4.4/getting-started/install-and-upgrade-guides/install-with-.zip: 4.5/getting-started/install-and-upgrade-guides/install-with-.zip.md
 4.4/getting-started/install-and-upgrade-guides/quick-install: 4.5/getting-started/install-and-upgrade-guides/quick-install.md
 4.4/getting-started/install-and-upgrade-guides/readme: 4.5/getting-started/install-and-upgrade-guides/README.md
 4.4/getting-started/install-and-upgrade-guides/run-in-docker/docker-compose-install: 4.5/getting-started/install-and-upgrade-guides/run-in-docker/docker-compose-install.md
 4.4/getting-started/install-and-upgrade-guides/run-in-docker/docker-images-install: 4.5/getting-started/install-and-upgrade-guides/run-in-docker/docker-images-install.md
 4.4/getting-started/install-and-upgrade-guides/run-in-docker/readme: 4.5/getting-started/install-and-upgrade-guides/run-in-docker/README.md
 4.4/getting-started/install-and-upgrade-guides/upgrade-guide: 4.5/getting-started/install-and-upgrade-guides/upgrade-guide.md
 4.4/getting-started/tutorial-getting-started-with-am/add-custom-claims-to-tokens: 4.5/getting-started/tutorial-getting-started-with-am/add-custom-claims-to-tokens.md
 4.4/getting-started/tutorial-getting-started-with-am/configure-a-flow: 4.5/getting-started/tutorial-getting-started-with-am/configure-a-flow.md
 4.4/getting-started/tutorial-getting-started-with-am/get-user-profile-information: 4.5/getting-started/tutorial-getting-started-with-am/get-user-profile-information.md
 4.4/getting-started/tutorial-getting-started-with-am/login-to-am-console: 4.5/getting-started/tutorial-getting-started-with-am/login-to-am-console.md
 4.4/getting-started/tutorial-getting-started-with-am/readme: 4.5/getting-started/tutorial-getting-started-with-am/README.md
 4.4/getting-started/tutorial-getting-started-with-am/secure-your-apis/configure-generic-oauth2-authorization-server: 4.5/getting-started/tutorial-getting-started-with-am/secure-your-apis/configure-generic-oauth2-authorization-server.md
 4.4/getting-started/tutorial-getting-started-with-am/secure-your-apis/configure-gravitee.io-access-management: 4.5/getting-started/tutorial-getting-started-with-am/secure-your-apis/configure-gravitee.io-access-management.md
 4.4/getting-started/tutorial-getting-started-with-am/secure-your-apis/readme: 4.5/getting-started/tutorial-getting-started-with-am/secure-your-apis/README.md
 4.4/getting-started/tutorial-getting-started-with-am/set-up-your-first-application: 4.5/getting-started/tutorial-getting-started-with-am/set-up-your-first-application.md
 4.4/guides/administration: 4.5/guides/administration.md
 4.4/guides/alerts/manage-alerts: 4.5/guides/alerts/manage-alerts.md
 4.4/guides/alerts/notification-channels: 4.5/guides/alerts/notification-channels.md
 4.4/guides/alerts/readme: 4.5/guides/alerts/README.md
 4.4/guides/am-expression-language: 4.5/guides/am-expression-language.md
 4.4/guides/applications: 4.5/guides/applications.md
 4.4/guides/audit-trail: 4.5/guides/audit-trail.md
 4.4/guides/auth-protocols/ciba: 4.5/guides/auth-protocols/ciba.md
 4.4/guides/auth-protocols/oauth-2.0/best-practices: 4.5/guides/auth-protocols/oauth-2.0/best-practices.md
 4.4/guides/auth-protocols/oauth-2.0/extension-grants: 4.5/guides/auth-protocols/oauth-2.0/extension-grants.md
 4.4/guides/auth-protocols/oauth-2.0/proof-key-for-code-exchange-pkce: 4.5/guides/auth-protocols/oauth-2.0/proof-key-for-code-exchange-pkce.md
 4.4/guides/auth-protocols/oauth-2.0/readme: 4.5/guides/auth-protocols/oauth-2.0/README.md
 4.4/guides/auth-protocols/oauth-2.0/refresh-tokens: 4.5/guides/auth-protocols/oauth-2.0/refresh-tokens.md
 4.4/guides/auth-protocols/oauth-2.0/which-flow-should-i-use: 4.5/guides/auth-protocols/oauth-2.0/which-flow-should-i-use.md
 4.4/guides/auth-protocols/open-banking: 4.5/guides/auth-protocols/open-banking.md
 4.4/guides/auth-protocols/openid-connect: 4.5/guides/auth-protocols/openid-connect.md
 4.4/guides/auth-protocols/readme: 4.5/guides/auth-protocols/README.md
 4.4/guides/auth-protocols/saml-2.0: 4.5/guides/auth-protocols/saml-2.0.md
 4.4/guides/auth-protocols/scim-2.0: 4.5/guides/auth-protocols/scim-2.0.md
 4.4/guides/auth-protocols/uma-2.0: 4.5/guides/auth-protocols/uma-2.0.md
 4.4/guides/bot-detection: 4.5/guides/bot-detection.md
 4.4/guides/branding/css-custom-variables-reference: 4.5/guides/branding/css-custom-variables-reference.md
 4.4/guides/branding/language-default-properties-reference: 4.5/guides/branding/language-default-properties-reference.md
 4.4/guides/branding/readme: 4.5/guides/branding/README.md
 4.4/guides/certificates: 4.5/guides/certificates/README.md
 4.4/guides/developer-contributions: 4.5/guides/developer-contributions.md
 4.4/guides/device-identifier: 4.5/guides/device-identifier.md
 4.4/guides/flows: 4.5/guides/flows.md
 4.4/guides/identity-providers/create-an-identity-provider: 4.5/guides/identity-providers/create-an-identity-provider.md
 4.4/guides/identity-providers/database-identity-providers/inline: 4.5/guides/identity-providers/database-identity-providers/inline.md
 4.4/guides/identity-providers/database-identity-providers/jdbc: 4.5/guides/identity-providers/database-identity-providers/jdbc.md
 4.4/guides/identity-providers/database-identity-providers/mongodb: 4.5/guides/identity-providers/database-identity-providers/mongodb.md
 4.4/guides/identity-providers/database-identity-providers/readme: 4.5/guides/identity-providers/database-identity-providers/README.md
 4.4/guides/identity-providers/enterprise-identity-providers/active-directory-ldap: 4.5/guides/identity-providers/enterprise-identity-providers/active-directory-ldap.md
 4.4/guides/identity-providers/enterprise-identity-providers/cas: 4.5/guides/identity-providers/enterprise-identity-providers/cas.md
 4.4/guides/identity-providers/enterprise-identity-providers/http-web-service: 4.5/guides/identity-providers/enterprise-identity-providers/http-web-service.md
 4.4/guides/identity-providers/enterprise-identity-providers/kerberos: 4.5/guides/identity-providers/enterprise-identity-providers/kerberos.md
 4.4/guides/identity-providers/enterprise-identity-providers/readme: 4.5/guides/identity-providers/enterprise-identity-providers/README.md
 4.4/guides/identity-providers/enterprise-identity-providers/saml-2.0: 4.5/guides/identity-providers/enterprise-identity-providers/saml-2.0.md
 4.4/guides/identity-providers/legal-identity-providers/franceconnect: 4.5/guides/identity-providers/legal-identity-providers/franceconnect.md
 4.4/guides/identity-providers/legal-identity-providers/readme: 4.5/guides/identity-providers/legal-identity-providers/README.md
 4.4/guides/identity-providers/readme: 4.5/guides/identity-providers/README.md
 4.4/guides/identity-providers/social-identity-providers/azure-ad: 4.5/guides/identity-providers/social-identity-providers/azure-ad.md
 4.4/guides/identity-providers/social-identity-providers/facebook: 4.5/guides/identity-providers/social-identity-providers/facebook.md
 4.4/guides/identity-providers/social-identity-providers/github: 4.5/guides/identity-providers/social-identity-providers/github.md
 4.4/guides/identity-providers/social-identity-providers/linkedin: 4.5/guides/identity-providers/social-identity-providers/linkedin.md
 4.4/guides/identity-providers/social-identity-providers/openid-connect: 4.5/guides/identity-providers/social-identity-providers/openid-connect.md
 4.4/guides/identity-providers/social-identity-providers/readme: 4.5/guides/identity-providers/social-identity-providers/README.md
 4.4/guides/identity-providers/social-identity-providers/salesforce: 4.5/guides/identity-providers/social-identity-providers/salesforce.md
 4.4/guides/identity-providers/social-identity-providers/twitter: 4.5/guides/identity-providers/social-identity-providers/twitter.md
 4.4/guides/identity-providers/user-and-role-mapping: 4.5/guides/identity-providers/user-and-role-mapping.md
 4.4/guides/login/adaptive-multi-factor-authentication: 4.5/guides/login/adaptive-multi-factor-authentication.md
 4.4/guides/login/hide-login-form: 4.5/guides/login/hide-login-form.md
 4.4/guides/login/identifier-first-login-flow: 4.5/guides/login/identifier-first-login-flow.md
 4.4/guides/login/passwordless-w3c-webauthn: 4.5/guides/login/passwordless-w3c-webauthn.md
 4.4/guides/login/readme: 4.5/guides/login/README.md
 4.4/guides/login/redirect-users-after-login: 4.5/guides/login/redirect-users-after-login.md
 4.4/guides/login/remember-authentication-device: 4.5/guides/login/remember-authentication-device.md
 4.4/guides/login/risk-based-mfa: 4.5/guides/login/risk-based-mfa.md
 4.4/guides/login/silent-reauthentication: 4.5/guides/login/silent-reauthentication.md
 4.4/guides/login/step-up-authentication: 4.5/guides/login/step-up-authentication.md
 4.4/guides/multi-factor-authentication/configure-mfa-for-an-application: 4.5/guides/multi-factor-authentication/configure-mfa-for-an-application.md
 4.4/guides/multi-factor-authentication/manage-user-mfa: 4.5/guides/multi-factor-authentication/manage-user-mfa.md
 4.4/guides/multi-factor-authentication/managing-factors/alternative-methods: 4.5/guides/multi-factor-authentication/managing-factors/alternative-methods.md
 4.4/guides/multi-factor-authentication/managing-factors/email: 4.5/guides/multi-factor-authentication/managing-factors/email.md
 4.4/guides/multi-factor-authentication/managing-factors/http-factor: 4.5/guides/multi-factor-authentication/managing-factors/http-factor.md
 4.4/guides/multi-factor-authentication/managing-factors/mfa-with-fido2: 4.5/guides/multi-factor-authentication/managing-factors/mfa-with-fido2.md
 4.4/guides/multi-factor-authentication/managing-factors/one-time-password-otp: 4.5/guides/multi-factor-authentication/managing-factors/one-time-password-otp.md
 4.4/guides/multi-factor-authentication/managing-factors/phone-call: 4.5/guides/multi-factor-authentication/managing-factors/phone-call.md
 4.4/guides/multi-factor-authentication/managing-factors/readme: 4.5/guides/multi-factor-authentication/managing-factors/README.md
 4.4/guides/multi-factor-authentication/managing-factors/recovery-codes: 4.5/guides/multi-factor-authentication/managing-factors/recovery-codes.md
 4.4/guides/multi-factor-authentication/managing-factors/sms: 4.5/guides/multi-factor-authentication/managing-factors/sms.md
 4.4/guides/multi-factor-authentication/mfa-brute-force-and-rate-limit: 4.5/guides/multi-factor-authentication/mfa-brute-force-and-rate-limit.md
 4.4/guides/multi-factor-authentication/mfa-policies: 4.5/guides/multi-factor-authentication/mfa-policies.md
 4.4/guides/multi-factor-authentication/readme: 4.5/guides/multi-factor-authentication/README.md
 4.4/guides/prologue: 4.5/guides/prologue.md
 4.4/guides/resources: 4.5/guides/resources.md
 4.4/guides/security-domains: 4.5/guides/security-domains.md
 4.4/guides/session-management: 4.5/guides/session-management.md
 4.4/guides/user-management/account-linking: 4.5/guides/user-management/account-linking.md
 4.4/guides/user-management/groups: 4.5/guides/user-management/groups.md
 4.4/guides/user-management/password-policy: 4.5/guides/user-management/password-policy.md
 4.4/guides/user-management/readme: 4.5/guides/user-management/README.md
 4.4/guides/user-management/roles: 4.5/guides/user-management/roles.md
 4.4/guides/user-management/scim-2.0: 4.5/guides/user-management/scim-2.0.md
 4.4/guides/user-management/self-service-account-management: 4.5/guides/user-management/self-service-account-management.md
 4.4/guides/user-management/user-attributes: 4.5/guides/user-management/user-attributes.md
 4.4/guides/user-management/user-consent: 4.5/guides/user-management/user-consent.md
 4.4/guides/user-management/user-registration: 4.5/guides/user-management/user-registration.md
 4.4/guides/user-management/users/password-options: 4.5/guides/user-management/users/password-options.md
 4.4/guides/user-management/users/readme: 4.5/guides/user-management/users/README.md
 4.4/overview/am-architecture: 4.5/overview/am-architecture.md
 4.4/overview/open-source-vs-enterprise-am/readme: 4.5/overview/open-source-vs-enterprise-am/README.md
 4.4/overview/plugins/compatibility-matrices: 4.5/overview/plugins/compatibility-matrices.md
 4.4/overview/plugins/readme: 4.5/overview/plugins/README.md
 4.4/readme: 4.5/README.md
 4.4/reference/am-api-reference: 4.5/reference/am-api-reference.md
 4.4/reference/azure-regions-for-saas-and-hybrid-deployments: README.md
 4.4/releases-and-changelog/changelog/am-4.3.x: 4.5/releases-and-changelog/changelog/am-4.5.x.md
 4.4/releases-and-changelog/changelog/am-4.4.x: 4.5/releases-and-changelog/changelog/am-4.5.x.md
 4.4/releases-and-changelog/changelog/readme: 4.5/releases-and-changelog/changelog/README.md
 4.4/releases-and-changelog/release-notes/am-4.3: 4.5/releases-and-changelog/release-notes/am-4.3.md
 4.4/releases-and-changelog/release-notes/am-4.4: 4.5/releases-and-changelog/release-notes/am-4.4.md
 4.4/releases-and-changelog/release-notes/readme: 4.5/releases-and-changelog/release-notes/README.md
 4.4/summary: 4.5/SUMMARY.md
