root: ./

structure:
  readme: get-started/README.md
  summary: SUMMARY.md
redirects:
 build: manage/README.md
 build/api-products: build/api-products.md
 build/configure-your-api-product: build/configure-your-api-product/README.md
 build/configure-your-api-product/api-product-configuration-reference: build/configure-your-api-product/api-product-configuration-reference.md
 build/configure-your-api-product/configure-product-deployment: build/configure-your-api-product/configure-product-deployment.md
 build/configure-your-api-product/manage-api-products-with-the-management-api: build/configure-your-api-product/manage-api-products-with-the-management-api.md
 build/configure-your-api-product/manage-members-and-ownership: build/configure-your-api-product/manage-members-and-ownership.md
 build/configure-your-api-product/manage-product-apis: build/configure-your-api-product/manage-product-apis.md
 build/configure-your-api-proxy: build/configure-your-api-proxy/README.md
 build/configure-your-api-proxy/apply-security-policies: build/configure-your-api-proxy/apply-security-policies.md
 build/configure-your-api-proxy/broadcast-messages-to-consumers: build/configure-your-api-proxy/broadcast-messages-to-consumers.md
 build/configure-your-api-proxy/configure-api-properties: build/configure-your-api-proxy/configure-api-properties.md
 build/configure-your-api-proxy/configure-api-resources: build/configure-your-api-proxy/configure-api-resources.md
 build/configure-your-api-proxy/configure-backend-security: build/configure-your-api-proxy/configure-backend-security.md
 build/configure-your-api-proxy/configure-cors: build/configure-your-api-proxy/configure-cors.md
 build/configure-your-api-proxy/configure-deployment: build/configure-your-api-proxy/configure-deployment.md
 build/configure-your-api-proxy/configure-entrypoints: build/configure-your-api-proxy/configure-entrypoints.md
 build/configure-your-api-proxy/configure-failover: build/configure-your-api-proxy/configure-failover.md
 build/configure-your-api-proxy/configure-flow-execution: build/configure-your-api-proxy/configure-flow-execution.md
 build/configure-your-api-proxy/configure-logging-and-tracing: build/configure-your-api-proxy/configure-logging-and-tracing.md
 build/configure-your-api-proxy/configure-notifications: build/configure-your-api-proxy/configure-notifications.md
 build/configure-your-api-proxy/establish-consumer-access: build/configure-your-api-proxy/establish-consumer-access.md
 build/configure-your-api-proxy/manage-general-settings: build/configure-your-api-proxy/manage-general-settings.md
 build/configure-your-api-proxy/manage-user-permissions: build/configure-your-api-proxy/manage-user-permissions.md
 build/configure-your-api-proxy/review-deployment-history: build/configure-your-api-proxy/review-deployment-history.md
 build/create-an-api-proxy: build/create-an-api-proxy.md
 build/secure-your-api-proxy: build/secure-your-api-proxy.md
 build/shared-policy-groups: build/shared-policy-groups.md
 observe: observability/README.md
 observe/api-dashboard: observe/api-dashboard.md
 observe/monitor-api-usage: observe/monitor-api-usage.md
 observe/monitor-endpoint-health: observe/monitor-endpoint-health.md
 observe/review-audit-logs: observe/review-audit-logs.md
 observe/view-api-logs: observe/view-api-logs.md
