root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
 getting-started/api-storage-and-control-options: README.md
 getting-started/api-storage-and-control-options/configure-the-gateway-to-load-apis-from-local-configmaps: README.md
 getting-started/api-storage-and-control-options/store-apis-in-local-configmaps: README.md
 getting-started/api-storage-and-control-options/use-a-central-apim-repository: README.md
 getting-started/installation: README.md
 getting-started/installation/cluster-vs-namespaced-install: README.md
 getting-started/installation/install-from-operatorhub: README.md
 getting-started/installation/install-with-helm: README.md
 getting-started/installation/rbac-customization: README.md
 getting-started/quickstart-guide: README.md
 gko-4.10: releases-and-changelog/release-notes/gko-4.4.md
 guides/create-your-own-helm-charts: README.md
 guides/db-less-mode: README.md
 guides/define-an-apim-service-account-for-gko: README.md
 guides/deploy-apis-to-a-gateway: README.md
 guides/export-an-api-as-a-kubernetes-manifest: README.md
 guides/gateway-api: README.md
 guides/gateway-api/dns-with-external-dns: README.md
 guides/gateway-api/full-example-of-configuring-self-hosted-gravitee-apim-with-k8s-gateway-api: README.md
 guides/gateway-api/httproute: README.md
 guides/gateway-api/tls-with-cert-manager: README.md
 guides/gko-http-client: README.md
 guides/gravitee-ingress-controller: README.md
 guides/kubernetes-crd-configuration-for-client-certificates: README.md
 guides/manage-api-documentation-pages: README.md
 guides/manage-api-groups-and-members: README.md
 guides/manage-api-key-subscriptions-with-gko: README.md
 guides/manage-jwt-subscriptions-with-gko: README.md
 guides/managing-dictionaries-via-automation-api: README.md
 guides/multi-environment-architecture: README.md
 guides/publish-apis-to-the-portal: README.md
 guides/templating: README.md
 new-release: README.md
 overview/custom-resource-definitions: overview/compatibility-and-limitations.md
 overview/custom-resource-definitions/apidefinition: overview/compatibility-and-limitations.md
 overview/custom-resource-definitions/apiresource: overview/compatibility-and-limitations.md
 overview/custom-resource-definitions/apiv4definition: overview/compatibility-and-limitations.md
 overview/custom-resource-definitions/application: overview/compatibility-and-limitations.md
 overview/custom-resource-definitions/dictionary-management-overview: overview/compatibility-and-limitations.md
 overview/custom-resource-definitions/dictionary-management-restrictions-and-validation: overview/compatibility-and-limitations.md
 overview/custom-resource-definitions/gatewayclassparameters: overview/compatibility-and-limitations.md
 overview/custom-resource-definitions/group: overview/compatibility-and-limitations.md
 overview/custom-resource-definitions/kafkaroute: overview/compatibility-and-limitations.md
 overview/custom-resource-definitions/managementcontext: overview/compatibility-and-limitations.md
 overview/custom-resource-definitions/managing-dictionaries-via-kubernetes-crd: overview/compatibility-and-limitations.md
 overview/custom-resource-definitions/notification: overview/compatibility-and-limitations.md
 overview/custom-resource-definitions/sharedpolicygroup: overview/compatibility-and-limitations.md
 overview/custom-resource-definitions/subscription: overview/compatibility-and-limitations.md
 overview/example-architecture: overview/compatibility-and-limitations.md
 releases-and-changelog/changelog/gko-4.10.x: releases-and-changelog/changelog/gko-4.3.x.md
 releases-and-changelog/changelog/gko-4.11.x: releases-and-changelog/changelog/gko-4.3.x.md
 releases-and-changelog/changelog/gko-4.4.x: releases-and-changelog/changelog/gko-4.3.x.md
 releases-and-changelog/changelog/gko-4.5.x: releases-and-changelog/changelog/gko-4.3.x.md
 releases-and-changelog/changelog/gko-4.6.x: releases-and-changelog/changelog/gko-4.3.x.md
 releases-and-changelog/changelog/gko-4.7.x: releases-and-changelog/changelog/gko-4.3.x.md
 releases-and-changelog/changelog/gko-4.8.x: releases-and-changelog/changelog/gko-4.3.x.md
 releases-and-changelog/changelog/gko-4.9.x: releases-and-changelog/changelog/gko-4.3.x.md
 releases-and-changelog/release-notes/gko-4.11: releases-and-changelog/release-notes/gko-4.4.md
 releases-and-changelog/release-notes/gko-4.12: releases-and-changelog/release-notes/gko-4.4.md
 releases-and-changelog/release-notes/gko-4.5: releases-and-changelog/release-notes/gko-4.4.md
 releases-and-changelog/release-notes/gko-4.6: releases-and-changelog/release-notes/gko-4.4.md
 releases-and-changelog/release-notes/gko-4.7: releases-and-changelog/release-notes/gko-4.4.md
 releases-and-changelog/release-notes/gko-4.8: releases-and-changelog/release-notes/gko-4.4.md
 releases-and-changelog/release-notes/gko-4.9: releases-and-changelog/release-notes/gko-4.4.md
