root: ./

​structure:
  readme: README.md
  summary: SUMMARY.md​

redirects:
  # guides/hybrid/install-on-docker: guides/hybrid.md
  # guides/hybrid/install-on-kubernetes: guides/hybrid.md
  guides/hybrid: apim/hybrid-installation-and-configuration-guides/next-gen-cloud/README.md
