root: ./

​structure:
  readme: README.md
  summary: SUMMARY.md​

redirects:
 getting-started/configuration/configure-alerts-and-notifications: gravitee-gateway/notifications.md
 guides/api-configuration/v4-api-configuration/documentation: configure-v4-apis/documentation.md
 installation-and-upgrades/repositories: configure-apim/repositories/README.md
 installation-and-upgrades/repositories/mongodb: configure-apim/repositories/mongodb.md
 reference/policy-reference/message-filtering: policies/message-filtering.md
 installation-and-upgrades/repositories/elasticsearch: configure-apim/repositories/elasticsearch.md
 installation-and-upgrades/repositories/redis: configure-apim/repositories/redis.md
 installation-and-upgrades/repositories/jdbc: configure-apim/repositories/jdbc.md
 installation-and-upgrades/advanced-hybrid-deployment: hybrid-deployment/overview.md
 guides/developer-portal/tools-and-features: developer-portal/settings.md
 installation-and-upgrades/upgrading-gravitee-api-management: install-and-upgrade/upgrade-guide.md
 overview/gravitee-apim-enterprise-edition/enterprise-support: overview/enterprise-edition.md
 using-the-product/managing-your-apis/resources: policies/resources.md
 using-the-product/managing-your-apis/preparing-apis-for-subscribers/plans/mtls: expose-apis/plans/mtls.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/d-h/data-logging-masking: policies/data-logging-masking.md
 most-common-use-cases/adding-role-based-access-control-to-your-jwt-plan: getting-started/use-case-tutorials/add-rbac-to-your-jwt-plan.md
 using-the-product/using-the-gravitee-api-management-components/general-configuration/secret-providers: configure-apim/sensitive-data-management/README.md
 installation-and-upgrades/repositories/cache: configure-apim/cache.md
 using-the-product/managing-your-apis/api-configuration/v4-api-configuration/endpoints: configure-v4-apis/endpoints/README.md
 using-the-product/managing-your-apis/create-apis/v2-apis-and-v4-apis-comparison: create-apis/v2-and-v4-api-comparison.md
 overview/apim-architecture: overview/architecture.md
 using-the-product/managing-your-apis/api-configuration/v4-api-configuration/endpoints/health-check: configure-v4-apis/health-checks.md
 using-the-product/managing-your-apis/api-configuration/v4-api-configuration/entrypoints/cors: configure-v4-apis/cors.md
 releases-and-changelog/release-notes: overview/release-notes/README.md
 using-the-product/managing-your-apis/create-apis/openapi-spec-import: create-apis/import-apis.md
 using-the-product/using-the-gravitee-api-management-components/developer-portal/publishing-and-managing-apis-with-the-gravitee-developer-portal/documentation: developer-portal/api-documentation.md
 guides/gravitee-expression-language: getting-started/gravitee-expression-language.md
 using-the-product/using-the-gravitee-api-management-components/developer-portal/configuring-and-customizing-the-gravitee-developer-portal/layout-and-theme-customization: developer-portal/layout-and-theme.md
 using-the-product/managing-your-apis/api-configuration/v2-api-configuration/general-proxy-settings: configure-v2-apis/proxy-settings.md
 using-the-product/federating-your-apis/3rd-party-providers/solace: federation/3rd-party-providers/solace.md
 using-the-product/managing-your-apis/api-configuration/v4-api-configuration/entrypoints/entrypoint-reference/webhook: configure-v4-apis/entrypoints/webhook.md
 using-the-product/managing-your-apis/policy-studio/v2-api-policy-studio: policies/v2-api-policy-studio.md
 using-the-product/managing-your-apis/preparing-apis-for-subscribers/plans/mtls/mtls-plans-overview: expose-apis/plans/mtls.md
 using-the-product/managing-your-apis/api-configuration/v4-api-configuration: configure-v4-apis/general-settings.md
 overview/plugins-and-api-definitions/gravitee-api-definitions-and-execution-engines: overview/execution-engine.md
 using-the-product/managing-your-apis/api-configuration/v4-api-configuration/version-history: configure-v4-apis/version-history.md
 using-the-product/managing-your-apis/policy-studio/policy-reference: policies/policy-reference.md
 using-the-product/managing-your-apis/create-apis: create-apis/overview.md
 getting-started/tutorials: getting-started/use-case-tutorials/README.md
 using-the-product/using-the-gravitee-api-management-components/developer-portal/webhook-subscription-management: developer-portal/webhook-subscriptions.md
 getting-started/install-gravitee-api-management/installing-a-gravitee-gateway-with-a-hybrid-deployment/advanced-hybrid-deployment: hybrid-deployment/overview.md
 using-the-product/managing-your-apis/api-configuration/v4-api-configuration/endpoints/v4-proxy-api-endpoints: configure-v4-apis/endpoints/README.md
 using-the-product/using-the-gravitee-api-management-components/developer-portal/configuring-and-customizing-the-gravitee-developer-portal/general-settings: developer-portal/settings.md
 using-the-product/managing-your-apis/preparing-apis-for-subscribers/subscriptions: expose-apis/subscriptions.md 
 installation-and-upgrades/advanced-hybrid-deployment/gateway-and-bridge-compatibility-versions: hybrid-deployment/overview.md
 using-the-product/using-the-gravitee-api-management-components/apim-console/configuring-notifications-and-alerts-for-your-apis: gravitee-gateway/alerts.md
 using-the-product/managing-your-apis/api-configuration/v4-api-configuration/entrypoints/entrypoint-reference/server-sent-events: configure-v4-apis/entrypoints/server-sent-events.md
 using-the-product/managing-your-apis/api-configuration/v4-api-configuration/entrypoints/v4-message-api-entrypoints/websocket: configure-v4-apis/entrypoints/websocket.md
 getting-started/install-and-upgrade-guides/install-on-kubernetes: install-and-upgrade/kubernetes.md
 using-the-product/using-the-gravitee-api-management-components/developer-portal: developer-portal/configuration-file.md
 using-the-product/managing-your-apis/create-apis/the-api-creation-wizard: create-apis/v4-api-creation-wizard.md
 using-the-product/managing-your-apis/api-measurement-tracking-and-analytics/audit-trail: api-analytics/audit-trail.md
 using-the-product/managing-your-apis/api-configuration/v4-api-configuration/audit-logs: configure-v4-apis/audit-logs.md
 guides/developer-portal/tools-and-features/documentation: developer-portal/api-documentation.md
 guides/policy-design/v2-api-policy-design-studio: policies/v2-api-policy-studio.md
 using-the-product/managing-your-apis/api-configuration/v4-api-configuration/entrypoints/v4-message-api-entrypoints/webhook: configure-v4-apis/entrypoints/webhook.md
 using-the-product/managing-your-apis/policy-studio: policies/v4-api-policy-studio.md
 using-the-product/managing-your-apis/create-apis/creating-and-publishing-an-api-with-the-management-api: getting-started/use-case-tutorials/create-and-publish-an-api-using-the-management-api.md
 using-the-product/administration/dXNlci1tYW: administration/organizations-and-environments.md
 overview/changelog/apim-4.5.x: overview/changelog/README.md
 releases-and-changelog/release-notes/apim-4.4: overview/release-notes/README.md
 using-the-product/managing-your-apis/api-configuration/v4-api-configuration/endpoints/endpoint-reference/kafka: configure-v4-apis/endpoints/kafka.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/i-k/keyless: policies/keyless.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/t-x/xml-threat-protection: policies/xml-threat-protection.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/l-p/oauth2/generic-oauth2-authorization-server: policies/oauth2/generic-oauth2-authorization-server.md
 using-the-product/using-the-gravitee-api-management-components/developer-portal/configuring-and-customizing-the-gravitee-developer-portal/apim-developer-portal: developer-portal/configuration-file.md
 using-the-product/federating-your-apis/3rd-party-providers/aws-api-gateway: federation/3rd-party-providers/aws-api-gateway.md
 getting-started/install-guides?_gl=1*1qp0kl9*_gcl_au*MTE0NDkzNTMzNi4xNzM3MTUzMDgz: install-and-upgrade/upgrade-guide.md
 guides/federation/federated-apis: federation/federated-apis.md
 getting-started/install-guides/install-on-docker?_gl=1*crt955*_gcl_au*MTc1NzM2MTQyMC4xNzM3NjMwNzc2: install-and-upgrade/docker/README.md
 using-the-product/using-the-gravitee-api-management-components/general-configuration/opentracing: gravitee-gateway/opentelemetry.md
 reference/policy-reference/groovy: policies/groovy.md
 using-the-product: getting-started/use-case-tutorials/README.md
 releases-and-changelog/changelog/apim-4.6.x: overview/changelog/apim-4.6.x.md
 using-the-product/managing-your-apis/api-configuration/v2-api-configuration/load-balancing-failover-and-health-checks: configure-v2-apis/load-balancing-failover-and-health-checks.md
 configure-apim/secrets-managers: configure-apim/sensitive-data-management/README.md
 reference/policy-reference/geoip-filtering: policies/geoip-filtering.md
 reference/policy-reference/traffic-shadowing: policies/traffic-shadowing.md
 using-the-product/managing-your-apis/api-configuration/v2-api-configuration/service-discovery: configure-v2-apis/service-discovery.md
 guides/api-configuration/v4-api-configuration/quality-of-service: configure-v4-apis/quality-of-service.md
 overview/plugins-and-api-definitions: getting-started/plugins/README.md
 using-the-product/manging-your-apis-with-gravitee-api-management/policy-studio/policies-for-your-apis/a-c/assign-attributes: policies/assign-attributes.md
 getting-started/upgrading-gravitee-api-management/breaking-changes-and-deprecated-functionality: install-and-upgrade/breaking-changes-and-deprecations.md
 getting-started/configuration/authentication-and-sso: administration/authentication/README.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis: policies/policy-reference.md
 getting-started/configuration/authentication/gravitee-am-authentication: administration/authentication/gravitee-access-management.md
 installation-and-upgrades/installing-with-rpm-packages: install-and-upgrade/rpm/README.md
 guides/create-apis/guides/create-apis/the-api-creation-wizard: create-apis/v4-api-creation-wizard.md
 getting-started/quickstart-guide: getting-started/use-case-tutorials/README.md
 overview/ee-vs-oss: overview/enterprise-edition.md
 gravitee-api-management/readme: README.md
 guides/developer-portal: developer-portal/settings.md
 reference/policy-reference/api-key: policies/api-key.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/a-c/assign-metrics: policies/assign-metrics.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/d-h/generate-http-signature: policies/generate-http-signature.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/a-c/avro-to-protobuf: policies/avro-to-protobuf.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/t-x/transform-headers: policies/transform-headers.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/t-x/traffic-shadowing: policies/traffic-shadowing.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/i-k/json-web-signature-jws: policies/jws-validator.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/d-h/geoip-filtering: policies/geoip-filtering.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/l-p/override-http-method: policies/override-http-method.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/t-x/transform-query-parameters: policies/transform-query-parameters.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/d-h/groovy: policies/groovy.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/l-p/oas-validation: policies/oas-validation.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/a-c/basic-authentication: policies/basic-authentication.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/a-c/cache: policies/cache.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/d-h/http-signature: policies/http-signature.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/r-s/resource-filtering: policies/resource-filtering.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/d-h/generate-jwt: policies/generate-jwt.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/r-s/request-content-limit: policies/request-content-limit.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/t-x/xslt: policies/xslt.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/i-k/json-threat-protection: policies/json-threat-protection.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/r-s/regex-threat-protection: policies/regex-threat-protection.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/r-s/rate-limit: policies/rate-limit.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/d-h/dynamic-routing: policies/dynamic-routing.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/a-c/api-key: policies/api-key.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/l-p/mock: policies/mock.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/a-c/assign-attributes: policies/assign-attributes.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/r-s/retry: policies/retry.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/a-c/circuit-breaker: policies/circuit-breaker.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/r-s/role-based-access-control-rbac: policies/role-based-access-control-rbac.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/i-k/json-validation: policies/json-validation.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/d-h/http-callout: policies/http-callout.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/r-s/request-validation: policies/request-validation.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/i-k/ip-filtering: policies/ip-filtering.md
 getting-started/install-guides/install-on-docker/quick-install-with-docker-compose: install-and-upgrade/docker/docker-compose.md
 using-the-product/managing-your-apis/api-configuration/v4-api-configuration/endpoints/endpoint-reference/rabbitmq: configure-v4-apis/endpoints/rabbitmq.md
 using-the-product/managing-your-apis/resources/authentication-providers: administration/authentication/authentication-providers.md
 using-the-product/federating-your-apis/3rd-party-providers/apigee-x: federation/3rd-party-providers/apigee-x.md
 installation-and-upgrades/installing-with-rpm-packages/installing-with-manual-install: install-and-upgrade/rpm/manual-install.md
 using-the-product/manging-your-apis-with-gravitee-api-management/preparing-apis-for-subscribers/plans/mtls/mtls-plans-overview: expose-apis/plans/mtls.md
 using-the-product/federating-your-apis/3rd-party-providers/ibm-api-connect: federation/3rd-party-providers/ibm-api-connect.md
 reference/bWFuYWdlbW: management-api/management-api-reference.md
 getting-started/configuration/configure-apim-management-api/internal-api#enable-https-support: management-api/internal-api.md
 getting-started/configuration/configure-apim-management-api/internal-api: management-api/internal-api.md
 getting-started/configuration/apim-gateway: gravitee-gateway/internal-api.md
 using-the-product/managing-your-apis: create-apis/overview.md
 getting-started/configuration/notifications: gravitee-gateway/alerts.md
 using-the-product/using-the-gravitee-api-management-components/apim-console: configure-apim/apim-components/apim-console.md
 getting-started/configuration/authentication-and-sso#gravitee-access-management-authentication: administration/authentication/gravitee-access-management.md
 installation-and-upgrades/install-gravitee-api-management: install-and-upgrade/upgrade-guide.md
 using-the-product/federating-your-apis: federation/overview.md
 installation-and-upgrades/repositories/elasticsearch#index-management-with-es-ilm: configure-apim/repositories/elasticsearch.md
 guides/developer-contributions/dev-guide-plugins: getting-started/plugins/customization.md
 configure-apim/secrets-managers#enabling-api-level-secrets: configure-v4-apis/api-level-secrets.md
 using-the-product/federating-your-apis/federated-apis: federation/federated-apis.md
 releases-and-changelog/changelog: overview/changelog/README.md
 reference/policy-reference/json-web-token-jwt: policies/jwt-validator.md
 using-the-product/using-the-gravitee-api-management-components/general-configuration/plans-and-policies/adding-a-policy: policies/v4-api-policy-studio.md
 overview/changelog/apim-4.2: releases-and-changelog/changelog/README.md
 getting-started/configuration/configure-repositories/elasticsearch#apim-api-configuration: configure-apim/repositories/elasticsearch.md
 releases-and-changelog/changelog/apim-4.4.x: overview/changelog/README.md
 overview/release-notes/apim-4.5: overview/release-notes/README.md
 releases-and-changelog/release-notes/gravitee-4.x/apim-4.0?utm_campaign=Gravitee%204.0%20Launch&utm_medium=email&_hsmi=268551278&_hsenc=p2ANqtz-98rc9Y9BF23YeJlS3_v8XkPquCUkttzd1dUhjnBi8a-MVjKluti9dCEAAoaC_MUW-3whMoonXZBSTFnJvlt4dlP-f1gQ&utm_content=268551278&utm_source=hs_email: overview/release-notes/README.md
 getting-started/install-guides: install-and-upgrade/upgrade-guide.md
 using-the-product/managing-your-apis/preparing-apis-for-subscribers/plans: expose-apis/plans/README.md
 using-the-product/managing-your-apis/api-configuration/v2-api-configuration/documentation: configure-v2-apis/documentation.md
 getting-started/install-guides/install-on-docker: install-and-upgrade/docker/README.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/l-p/oauth2: policies/oauth2/README.md
 using-the-product/using-the-gravitee-api-management-components/general-configuration-1: configure-apim/apim-components/management-api.md
 getting-started/configuration/configure-apim-management-api/internal-api-1: management-api/internal-api.md
 4.3/guides/create-apis/guides/create-apis/the-api-creation-wizard: 4.3/guides/create-apis/the-api-creation-wizard/README.md
 4.2/overview/changelog/apim-4.2: 4.2/releases-and-changelog/changelog/apim-4.2.x.md
 overview/gravitee-api-definitions-and-execution-engines/engine-comparisons: overview/execution-engine.md
 using-the-product/using-the-gravitee-api-management-components/general-configuration/plans-and-policies/custom-policies: policies/custom-policies.md
 policies/avro-to-json-1: policies/avro-to-json.md
 policies/avro-to-protobuf-1: policies/avro-to-protobuf.md
 using-the-product/administration/authentication/azure-regions-for-saas-and-hybrid-deployments: administration/authentication/azure-entra-id.md
 v/4.0-5/releases-and-changelog/changelogs/apim-4.0.x-changelog: 4.0/releases-and-changelog/changelog/apim-4.0.x.md
 using-the-product/using-the-gravitee-api-management-components/general-configuration/shared-policy-groups/default-ai-flows-overview: policies/shared-policy-groups.md
 overview/plugins-and-api-definitions/plugins/plugins: getting-started/plugins/README.md
 overview/plugins-and-api-definitions/gravitee-api-definitions-and-execution-engines/engine-comparisons: overview/execution-engine.md
 installation-and-upgrades/installing-on-openshift: install-and-upgrade/openshift.md
 installation-and-upgrades/installing-with-rpm-packages/installing-with-quick-full-stack-install: install-and-upgrade/rpm/quick-install.md
 
 
