root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
 4.6/community-and-support/community/readme: 4.7/community-and-support/community/README.md
 4.6/community-and-support/enterprise-support: 4.7/community-and-support/enterprise-support.md
 4.6/getting-started/api-storage-and-control-options/configure-the-gateway-to-load-apis-from-local-configmaps: 4.7/getting-started/api-storage-and-control-options/configure-the-gateway-to-load-apis-from-local-configmaps.md
 4.6/getting-started/api-storage-and-control-options/readme: 4.7/getting-started/api-storage-and-control-options/README.md
 4.6/getting-started/api-storage-and-control-options/store-apis-in-local-configmaps: 4.7/getting-started/api-storage-and-control-options/store-apis-in-local-configmaps.md
 4.6/getting-started/api-storage-and-control-options/use-a-central-apim-repository: 4.7/getting-started/api-storage-and-control-options/use-a-central-apim-repository.md
 4.6/getting-started/installation/cluster-vs-namespaced-install: 4.7/getting-started/installation/cluster-vs-namespaced-install.md
 4.6/getting-started/installation/install-with-helm: 4.7/getting-started/installation/install-with-helm.md
 4.6/getting-started/installation/rbac-customization: 4.7/getting-started/installation/rbac-customization.md
 4.6/getting-started/installation/readme: 4.7/getting-started/installation/README.md
 4.6/getting-started/quickstart-guide: 4.7/getting-started/quickstart-guide.md
 4.6/guides/create-your-own-helm-charts: 4.7/guides/create-your-own-helm-charts.md
 4.6/guides/db-less-mode: 4.7/guides/db-less-mode.md
 4.6/guides/define-an-apim-service-account-for-gko: 4.7/guides/define-an-apim-service-account-for-gko.md
 4.6/guides/deploy-apis-to-a-gateway: 4.7/guides/deploy-apis-to-a-gateway.md
 4.6/guides/export-an-api-as-a-kubernetes-manifest: 4.7/guides/export-an-api-as-a-kubernetes-manifest.md
 4.6/guides/gravitee-ingress-controller: 4.7/guides/gravitee-ingress-controller.md
 4.6/guides/manage-api-documentation-pages: 4.7/guides/manage-api-documentation-pages.md
 4.6/guides/manage-api-groups-and-members: 4.7/guides/manage-api-groups-and-members.md
 4.6/guides/manage-jwt-subscriptions-with-gko: 4.7/guides/manage-jwt-subscriptions-with-gko.md
 4.6/guides/multi-environment-architecture: 4.7/guides/multi-environment-architecture.md
 4.6/guides/publish-apis-to-the-portal: 4.7/guides/publish-apis-to-the-portal.md
 4.6/guides/templating: 4.7/guides/templating.md
 4.6/overview/compatibility-and-limitations: 4.7/overview/compatibility-and-limitations.md
 4.6/overview/custom-resource-definitions/apidefinition: 4.7/overview/custom-resource-definitions/apidefinition.md
 4.6/overview/custom-resource-definitions/apiresource: 4.7/overview/custom-resource-definitions/apiresource.md
 4.6/overview/custom-resource-definitions/apiv4definition: 4.7/overview/custom-resource-definitions/apiv4definition.md
 4.6/overview/custom-resource-definitions/application: 4.7/overview/custom-resource-definitions/application.md
 4.6/overview/custom-resource-definitions/managementcontext: 4.7/overview/custom-resource-definitions/managementcontext.md
 4.6/overview/custom-resource-definitions/readme: 4.7/overview/custom-resource-definitions/README.md
 4.6/overview/custom-resource-definitions/subscription: 4.7/overview/custom-resource-definitions/subscription.md
 4.6/overview/example-architecture: 4.7/overview/example-architecture.md
 4.6/readme: 4.7/README.md
 4.6/reference/api-reference: 4.7/reference/api-reference.md
 4.6/releases-and-changelog/changelog/gko-4.6.x: 4.7/releases-and-changelog/changelog/gko-4.6.x.md
 4.6/releases-and-changelog/changelog/readme: 4.7/releases-and-changelog/changelog/README.md
 4.6/releases-and-changelog/release-notes/gko-4.6: README.md
 4.6/releases-and-changelog/release-notes/readme: 4.7/releases-and-changelog/release-notes/README.md
 4.6/summary: 4.7/SUMMARY.md