name: Markdown Diff Notifier

on:
  push:
    branches:
      - main

jobs:
  notify-significant-changes:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set SHAs
        run: |
          echo "PREVIOUS_SHA=$(git rev-parse HEAD^1)" >> "$GITHUB_ENV"
          echo "CURRENT_SHA=$(git rev-parse HEAD)" >> "$GITHUB_ENV"

      - name: Decode summarization script from secret
        run: echo "$MARKDOWN_SUMMARIZER_SCRIPT" | base64 -d > summarize_diffs.py
        env:
          MARKDOWN_SUMMARIZER_SCRIPT: ${{ secrets.MARKDOWN_SUMMARIZER_SCRIPT }}
      
      - name: Validate summarization script
        run: |
          if [ ! -s summarize_diffs.py ]; then
            echo "❌ Error: summarize_diffs.py was not created properly from secret."
            exit 1
          else
            echo "✅ summarize_diffs.py successfully created."
          fi
          
      - name: Run summarizer script
        run: |
          python3 summarize_diffs.py "$(pwd)/docs" "$PREVIOUS_SHA" "$CURRENT_SHA" "https://github.com/${{ github.repository }}" > changes.json

      - name: Create Slack message from changes
        id: format
        run: |
          jq -r '.[] | "\n*\(.title)*\n<\(.link)>\n\(.summary)"' changes.json > slack_message.txt
          if [ ! -s slack_message.txt ]; then
            echo "No significant changes. Skipping notification."
            echo "send=false" >> "$GITHUB_ENV"
          else
            echo "send=true" >> "$GITHUB_ENV"
          fi

      - name: Send to Slack
        if: env.send == 'true'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload-file-path: slack_message.txt
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
