name: Notify Slack on GitBook Sync

on:
  push:
    branches:
      - main

jobs:
  notify-if-gitbook:
    runs-on: ubuntu-latest
    steps:
      - name: Check if update is from a pull request
        id: check
        run: |
          MESSAGE="${{ github.event.head_commit.message }}"
          if [[ "$MESSAGE" =~ ^Merge\ pull\ request ]]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Get list of changed files
        if: steps.check.outputs.skip == 'false'
        id: files
        run: |
          FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | paste -sd ', ' -)
          echo "files=$FILES" >> $GITHUB_OUTPUT

      - name: Build Slack payload
        run: |
          FILE_LIST=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
          FORMATTED=""
          while read -r FILE; do
            LINK="• <https://github.com/${{ github.repository }}/blob/main/$FILE|$FILE>"
            FORMATTED="$FORMATTED$LINK\n"
          done <<< "$FILE_LIST"
          FORMATTED=$(echo -e "$FORMATTED" | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')

          jq -n \
            --arg repo "${{ github.repository }}" \
            --arg branch "main" \
            --arg author "${{ github.event.head_commit.author.name }}" \
            --arg sha "${{ github.sha }}" \
            --arg message "${{ github.event.head_commit.message }}" \
            --arg files "$FORMATTED" \
            '{
              text: ":book: GitBook Sync Detected!",
              blocks: [
                {
                  type: "section",
                  text: {
                    type: "mrkdwn",
                    text: "*Repository:* `\($repo)`\n*Branch:* `\($branch)`\n*Author:* `\($author)`\n*Commit:* <https://github.com/\($repo)/commit/\($sha)|\($sha)>\n*Message:* \($message)\n*Changed files:*\n\($files)"
                  }
                }
              ]
            }' > payload.json

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload-file-path: payload.json
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
