name: notify-if-not-pr

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Setting up job"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: gravitee-io/gravitee-platform-docs
          fetch-depth: 0
          ssh-strict: true
          persist-credentials: true
          clean: true
          sparse-checkout-cone-mode: true
          fetch-tags: false
          lfs: false
          submodules: false
          set-safe-directory: true

      - name: Check if this is a PR merge
        id: pr-check
        run: |
          MESSAGE="${{ github.event.head_commit.message }}"
          if [[ "$MESSAGE" =~ ^Merge\ pull\ request ]]; then
            echo "This is a PR merge. Skipping."
            echo "send=false" >> "$GITHUB_ENV"
          else
            echo "This is NOT a PR merge. Proceeding."
            echo "send=true" >> "$GITHUB_ENV"
          fi

      - name: Build Slack payload
        if: env.send == 'true'
        id: payload
        run: |
          CURRENT_SHA="${{ github.sha }}"
          PREVIOUS_SHA=$(git rev-parse "$CURRENT_SHA^1")

          echo "PREVIOUS_SHA: $PREVIOUS_SHA"
          echo "CURRENT_SHA: $CURRENT_SHA"

          FILE_LIST=$(git diff --name-only "$PREVIOUS_SHA" "$CURRENT_SHA" | grep '^docs/' || true)

          if [[ -z "$FILE_LIST" ]]; then
            echo "No docs/ files changed. Skipping notification."
            echo "send=false" >> "$GITHUB_ENV"
            exit 0
          fi

          FILE_LINKS=""
          while read -r FILE; do
            LINK="• https://github.com/gravitee-io/gravitee-platform-docs/blob/main/$FILE"
            FILE_LINKS="${FILE_LINKS}${LINK}\n"
          done <<< "$FILE_LIST"

          DIFF_URL="https://github.com/gravitee-io/gravitee-platform-docs/compare/$PREVIOUS_SHA...$CURRENT_SHA"
          COMMIT_URL="https://github.com/gravitee-io/gravitee-platform-docs/commit/$CURRENT_SHA"

          echo -e ":book: GitBook Sync Detected!\nRepository: gravitee-io/gravitee-platform-docs\nBranch: main\nAuthor: ${{ github.actor }}\nCommit: $COMMIT_URL\nMessage: ${{ github.event.head_commit.message }}\nDiff: $DIFF_URL\nChanged files:\n$FILE_LINKS" > slack_message.txt

          jq -Rs '{ text: . }' slack_message.txt > payload.json

      - name: Send Slack notification
        if: env.send == 'true'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload-file-path: payload.json
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Post Checkout code
        run: echo "Code checkout complete"

      - name: Complete job
        run: echo "Job done"
