name: Notify Slack on GitBook Sync

on:
  push:
    branches:
      - main

jobs:
  notify-if-not-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Skip if commit is a PR merge
        id: check
        run: |
          MESSAGE="${{ github.event.head_commit.message }}"
          if [[ "$MESSAGE" =~ ^Merge\ pull\ request ]]; then
            echo "This is a PR merge. Skipping."
            echo "send=false" >> $GITHUB_OUTPUT
          else
            echo "This is NOT a PR merge. Proceeding."
            echo "send=true" >> $GITHUB_OUTPUT
          fi

      - name: Build Slack payload
        if: steps.check.outputs.skip == 'false'
        run: |
          # Get only docs/ files from the current commit
          FILE_LIST=$(git show --pretty="" --name-only ${{ github.sha }} | grep '^docs/' || true)

          if [[ -z "$FILE_LIST" ]]; then
            echo "No docs/ files changed. Skipping notification."
            echo "send=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Format into bullet list with links
          FILE_BLOCKS=""
          while read -r FILE; do
            FILE_BLOCKS="${FILE_BLOCKS}• <https://github.com/${{ github.repository }}/blob/main/$FILE|$FILE>\n"
          done <<< "$FILE_LIST"

          echo -e "$FILE_BLOCKS" > formatted_files.txt

          DIFF_URL="https://github.com/${{ github.repository }}/compare/${{ github.event.before }}...${{ github.sha }}"

          jq -n \
            --rawfile files formatted_files.txt \
            --arg repo "${{ github.repository }}" \
            --arg branch "main" \
            --arg author "${{ github.event.head_commit.author.name }}" \
            --arg sha "${{ github.sha }}" \
            --arg message "${{ github.event.head_commit.message }}" \
            --arg diff "$DIFF_URL" \
            '{
              text: ":book: GitBook Sync Detected!",
              blocks: [
                {
                  type: "section",
                  text: {
                    type: "mrkdwn",
                    text: "*Repository:* `\($repo)`\n*Branch:* `\($branch)`\n*Author:* `\($author)`\n*Commit:* <https://github.com/\($repo)/commit/\($sha)|\($sha)>\n*Message:* \($message)\n*Diff:* <\($diff)|View changes>\n*Changed files:*\n\($files)"
                  }
                }
              ]
            }' > payload.json

          echo "send=true" >> $GITHUB_OUTPUT

      - name: Send Slack notification
        if: steps.payload.outputs.send == 'true'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload-file-path: payload.json
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
