name: Notify Slack on Merge to Main

on:
  pull_request:
    types:
      - closed

jobs:
  notify-slack:
    if: >
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # To get previous commit

      - name: Build Slack payload
        id: payload
        run: |
          CURRENT_SHA="${{ github.event.pull_request.merge_commit_sha }}"
          PREVIOUS_SHA=$(git rev-parse "$CURRENT_SHA^1")

          DIFF_URL="https://github.com/${{ github.repository }}/compare/$PREVIOUS_SHA...$CURRENT_SHA"
          COMMIT_URL="https://github.com/${{ github.repository }}/commit/$CURRENT_SHA"

          FILE_LIST=$(git diff --name-only "$PREVIOUS_SHA" "$CURRENT_SHA" | grep '\.md$' || true)
          FILE_LINKS=""
          while read -r FILE; do
            LINK="• https://github.com/${{ github.repository }}/blob/main/$FILE"
            FILE_LINKS="${FILE_LINKS}${LINK}\n"
          done <<< "$FILE_LIST"

          echo -e "$FILE_LINKS" > formatted_files.txt

          jq -n \
            --rawfile files formatted_files.txt \
            --arg pr_title "${{ github.event.pull_request.title }}" \
            --arg pr_url "${{ github.event.pull_request.html_url }}" \
            --arg author "${{ github.actor }}" \
            --arg repo "${{ github.repository }}" \
            --arg sha "$CURRENT_SHA" \
            --arg diff "$DIFF_URL" \
            '{
              text: ":tada: Pull request merged to `main`!\n*Title:* <\($pr_url)|\($pr_title)>\n*Author:* \($author)\n*Commit:* https://github.com/\($repo)/commit/\($sha)\n*Diff:* \($diff)\n*Changed files:*\n\($files)"
            }' > payload.json

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload-file-path: payload.json
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
