name: Vale Linting
on:
  pull_request:
    paths:
      - '**.md'

permissions:
  pull-requests: write

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: errata-ai/vale-action@v2
        with:
          files: docs/
          reporter: github-pr-review
          vale_flags: "--glob='!**/SUMMARY.md' --glob='!**/CONTRIBUTING.md'"
